In [1]:
print("Частина 2. Аналіз Individual Household Electric Power Consumption Dataset")

Частина 2. Аналіз Individual Household Electric Power Consumption Dataset

In [2]:
import pandas as pd
import timeit

df = pd.read_csv(
    "data_power/household_power_consumption.txt",
    sep=";",
    low_memory=False
)

print("Перші 5 рядків датасету:")
display(df.head())

print("Розмір датасету:", df.shape)

Перші 5 рядків датасету:

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

Розмір датасету: (2075259, 9)

In [3]:
print("Кількість пропусків до очищення:")
print(df.isnull().sum())

numeric_cols = [
    "Global_active_power",
    "Global_reactive_power",
    "Voltage",
    "Global_intensity",
    "Sub_metering_1",
    "Sub_metering_2",
    "Sub_metering_3"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df_clean = df.dropna()

print("Розмір датасету після очищення:", df_clean.shape)

print("Кількість пропусків після очищення:")
print(df_clean.isnull().sum())

df_clean.to_csv("household_power_clean.csv", index=False)
print("Очищений датасет збережено у файл household_power_clean.csv")

Кількість пропусків до очищення:
Date                         0
Time                         0
Global_active_power          0
Global_reactive_power        0
Voltage                      0
Global_intensity             0
Sub_metering_1               0
Sub_metering_2               0
Sub_metering_3           25979
dtype: int64
Розмір датасету після очищення: (2049280, 9)
Кількість пропусків після очищення:
Date                     0
Time                     0
Global_active_power      0
Global_reactive_power    0
Voltage                  0
Global_intensity         0
Sub_metering_1           0
Sub_metering_2           0
Sub_metering_3           0
dtype: int64
Очищений датасет збережено у файл household_power_clean.csv

In [4]:
print("Завдання 1. Обрати всі записи, у яких Global_active_power > 5 кВт")

def power_over_5kw():
    return df_clean[df_clean["Global_active_power"] > 5]

result_1 = power_over_5kw()

print("Кількість записів:", len(result_1))
display(result_1.head(20))

Завдання 1. Обрати всі записи, у яких Global_active_power > 5 кВт
Кількість записів: 17547

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0
11,16/12/2006,17:35:00,5.412,0.470,232.78,23.2,0.0,1.0,17.0
12,16/12/2006,17:36:00,5.224,0.478,232.99,22.4,0.0,1.0,16.0
13,16/12/2006,17:37:00,5.268,0.398,232.91,22.6,0.0,2.0,17.0
20,16/12/2006,17:44:00,5.894,0.000,232.69,25.4,0.0,0.0,16.0
21,16/12/2006,17:45:00,7.706,0.000,230.98,33.2,0.0,0.0,17.0
22,16/12/2006,17:46:00,7.026,0.000,232.21,30.6,0.0,0.0,16.0
23,16/12/2006,17:47:00,5.174,0.000,234.19,22.0,0.0,0.0,17.0
41,16/12/2006,18:05:00,6.052,0.192,232.93,26.2,0.0,37.0,17.0
42,16/12/2006,18:06:00,6.752,0.186,232.12,29.0,0.0,36.0,17.0
43,16/12/2006,18:07:00,6.474,0.144,231.85,27.8,0.0,37.0,16.0
44,16/12/2006,18:08:00,6.308,0.116,232.25,27.0,0.0,36.0,17.0
71,16/12/2006,18:35:00,6.072,0.000,232.48,26.4,0.0,27.0,17.0
461,17/12/2006,01:05:00,5.282,0.150,237.38,22.4,0.0,35.0,0.0
465,17/12/2006,01:09:00,5.242,0.178,239.49,21.8,0.0,37.0,0.0
469,17/12/2006,01:13:00,5.254,0.214,238.15,22.0,0.0,35.0,0.0
470,17/12/2006,01:14:00,5.246,0.230,237.91,22.0,0.0,36.0,0.0
471,17/12/2006,01:15:00,5.216,0.210,237.44,22.0,0.0,36.0,0.0

In [5]:
print("Завдання 2. Обрати записи, де струм 19-20 А, а Sub_metering_2 > Sub_metering_1 + Sub_metering_3")

def current_19_20():
    data = df_clean[
        (df_clean["Global_intensity"] >= 19) &
        (df_clean["Global_intensity"] <= 20)
    ]
    
    result = data[
        data["Sub_metering_2"] > 
        (data["Sub_metering_1"] + data["Sub_metering_3"])
    ]
    
    return result

result_2 = current_19_20()

print("Кількість записів:", len(result_2))
display(result_2.head(20))

Завдання 2. Обрати записи, де струм 19-20 А, а Sub_metering_2 > Sub_metering_1 + Sub_metering_3
Кількість записів: 2153

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
45,16/12/2006,18:09:00,4.464,0.136,234.66,19.0,0.0,37.0,16.0
460,17/12/2006,01:04:00,4.582,0.258,238.08,19.6,0.0,13.0,0.0
464,17/12/2006,01:08:00,4.618,0.104,239.61,19.6,0.0,27.0,0.0
475,17/12/2006,01:19:00,4.636,0.140,237.37,19.4,0.0,36.0,0.0
476,17/12/2006,01:20:00,4.634,0.152,237.17,19.4,0.0,35.0,0.0
477,17/12/2006,01:21:00,4.652,0.142,237.92,19.4,0.0,36.0,0.0
508,17/12/2006,01:52:00,4.622,0.240,239.59,19.2,0.0,37.0,0.0
944,17/12/2006,09:08:00,4.762,0.088,237.44,20.0,0.0,38.0,0.0
945,17/12/2006,09:09:00,4.506,0.088,237.25,19.0,0.0,38.0,0.0
1051,17/12/2006,10:55:00,4.444,0.136,235.97,19.2,2.0,50.0,17.0
2999,18/12/2006,19:23:00,4.642,0.400,233.62,19.8,0.0,36.0,0.0
3000,18/12/2006,19:24:00,4.580,0.390,232.51,19.6,0.0,37.0,0.0
3941,19/12/2006,11:05:00,4.602,0.000,237.24,19.4,0.0,73.0,0.0
3942,19/12/2006,11:06:00,4.698,0.000,237.94,19.6,0.0,73.0,0.0
3943,19/12/2006,11:07:00,4.702,0.000,238.03,19.6,0.0,73.0,0.0
3944,19/12/2006,11:08:00,4.702,0.080,237.81,19.6,0.0,73.0,0.0
3945,19/12/2006,11:09:00,4.660,0.084,236.58,19.6,0.0,73.0,0.0
3946,19/12/2006,11:10:00,4.618,0.072,235.53,19.6,0.0,72.0,0.0
3947,19/12/2006,11:11:00,4.668,0.086,236.91,19.6,0.0,73.0,0.0
3948,19/12/2006,11:12:00,4.542,0.078,236.83,19.2,0.0,72.0,0.0

In [6]:
print("Завдання 3. Обрати випадково 500000 записів без повторів і знайти середні значення трьох груп споживання")

def random_500k():
    return df_clean.sample(
        n=500000,
        replace=False,
        random_state=42
    )

sample_500k = random_500k()

means = sample_500k[
    ["Sub_metering_1", "Sub_metering_2", "Sub_metering_3"]
].mean()

print("Середні значення:")
print(means)

Завдання 3. Обрати випадково 500000 записів без повторів і знайти середні значення трьох груп споживання
Середні значення:
Sub_metering_1    1.119258
Sub_metering_2    1.308912
Sub_metering_3    6.452950
dtype: float64

In [7]:
print("Завдання 4. Після 18:00, понад 6 кВт, основне споживання припадає на групу 2")

def evening_consumption():
    data = df_clean[
        (df_clean["Time"] > "18:00:00") &
        (df_clean["Global_active_power"] > 6)
    ]
    
    data = data[
        (data["Sub_metering_2"] > data["Sub_metering_1"]) &
        (data["Sub_metering_2"] > data["Sub_metering_3"])
    ]
    
    half = len(data) // 2
    
    first_half = data.iloc[:half]
    second_half = data.iloc[half:]
    
    result_first = first_half.iloc[::3]
    result_second = second_half.iloc[::4]
    
    return pd.concat([result_first, result_second])

result_4 = evening_consumption()

print("Кількість записів:", len(result_4))
display(result_4.head(20))

Завдання 4. Після 18:00, понад 6 кВт, основне споживання припадає на групу 2
Кількість записів: 310

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
41,16/12/2006,18:05:00,6.052,0.192,232.93,26.2,0.0,37.0,17.0
44,16/12/2006,18:08:00,6.308,0.116,232.25,27.0,0.0,36.0,17.0
17494,28/12/2006,20:58:00,6.386,0.374,236.63,27.0,1.0,36.0,17.0
17498,28/12/2006,21:02:00,8.088,0.262,235.50,34.4,1.0,72.0,17.0
17501,28/12/2006,21:05:00,7.230,0.152,235.22,30.6,1.0,73.0,17.0
17504,28/12/2006,21:08:00,7.352,0.000,235.45,31.2,1.0,73.0,17.0
17507,28/12/2006,21:11:00,9.048,0.000,231.48,39.0,34.0,71.0,16.0
17510,28/12/2006,21:14:00,9.118,0.108,231.18,39.4,36.0,72.0,16.0
17513,28/12/2006,21:17:00,7.040,0.130,233.27,30.2,37.0,38.0,17.0
18952,29/12/2006,21:16:00,6.146,0.116,230.53,26.6,0.0,70.0,0.0
18955,29/12/2006,21:19:00,6.184,0.138,231.57,26.6,0.0,70.0,0.0
18958,29/12/2006,21:22:00,6.214,0.120,230.53,26.8,0.0,70.0,0.0
18961,29/12/2006,21:25:00,6.086,0.000,229.04,26.6,0.0,69.0,0.0
18965,29/12/2006,21:29:00,6.660,0.000,229.00,29.0,0.0,69.0,17.0
19024,29/12/2006,22:28:00,6.300,0.294,236.08,26.8,0.0,65.0,17.0
19027,29/12/2006,22:31:00,6.426,0.282,234.80,27.4,0.0,73.0,17.0
19030,29/12/2006,22:34:00,6.238,0.268,235.12,26.4,0.0,73.0,17.0
31719,7/1/2007,18:03:00,6.458,0.000,230.85,27.8,0.0,69.0,16.0
31722,7/1/2007,18:06:00,6.676,0.000,230.88,28.8,0.0,69.0,16.0
31725,7/1/2007,18:09:00,6.326,0.150,231.77,27.6,0.0,62.0,17.0

In [8]:
print("Профілювання часу виконання функцій за допомогою timeit")

t1 = timeit.timeit(lambda: power_over_5kw(), number=100)
t2 = timeit.timeit(lambda: current_19_20(), number=100)
t3 = timeit.timeit(lambda: random_500k(), number=10)
t4 = timeit.timeit(lambda: evening_consumption(), number=100)

print("Вибірка 1:")
print("Час за 100 запусків:", t1)
print("Середній час:", t1 / 100)

print("\nВибірка 2:")
print("Час за 100 запусків:", t2)
print("Середній час:", t2 / 100)

print("\nВибірка 3:")
print("Час за 10 запусків:", t3)
print("Середній час:", t3 / 10)

print("\nВибірка 4:")
print("Час за 100 запусків:", t4)
print("Середній час:", t4 / 100)

Профілювання часу виконання функцій за допомогою timeit
Вибірка 1:
Час за 100 запусків: 0.8226876999251544
Середній час: 0.008226876999251544

Вибірка 2:
Час за 100 запусків: 1.936364599969238
Середній час: 0.01936364599969238

Вибірка 3:
Час за 10 запусків: 5.33165069995448
Середній час: 0.533165069995448

Вибірка 4:
Час за 100 запусків: 37.942883000243455
Середній час: 0.37942883000243455

In [9]:
print("Нормалізація вибраного датасету")

numeric_cols = [
    "Global_active_power",
    "Global_reactive_power",
    "Voltage",
    "Global_intensity",
    "Sub_metering_1",
    "Sub_metering_2",
    "Sub_metering_3"
]

df_normalized = df_clean.copy()

for col in numeric_cols:
    df_normalized[col] = (
        (df_clean[col] - df_clean[col].min()) /
        (df_clean[col].max() - df_clean[col].min())
    )

display(df_normalized[numeric_cols].head())

Нормалізація вибраного датасету

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,0.374796,0.300719,0.376090,0.377593,0.0,0.0125,0.548387
1,0.478363,0.313669,0.336995,0.473029,0.0,0.0125,0.516129
2,0.479631,0.358273,0.326010,0.473029,0.0,0.0250,0.548387
3,0.480898,0.361151,0.340549,0.473029,0.0,0.0125,0.548387
4,0.325005,0.379856,0.403231,0.323651,0.0,0.0125,0.548387

In [10]:
print("Стандартизація вибраного датасету")

df_standardized = df_clean.copy()

for col in numeric_cols:
    df_standardized[col] = (
        (df_clean[col] - df_clean[col].mean()) /
        df_clean[col].std()
    )

display(df_standardized[numeric_cols].head())

Стандартизація вибраного датасету

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2.955076,2.610720,-1.851816,3.098788,-0.182337,-0.051274,1.249420
1,4.037084,2.770405,-2.225274,4.133799,-0.182337,-0.051274,1.130897
2,4.050325,3.320431,-2.330213,4.133799,-0.182337,0.120487,1.249420
3,4.063566,3.355916,-2.191323,4.133799,-0.182337,-0.051274,1.249420
4,2.434881,3.586572,-1.592555,2.513781,-0.182337,-0.051274,1.249420

In [11]:
print("Коефіцієнт Пірсона та Спірмена для Global_active_power і Global_intensity")

pearson = df_clean["Global_active_power"].corr(
    df_clean["Global_intensity"],
    method="pearson"
)

spearman = df_clean["Global_active_power"].corr(
    df_clean["Global_intensity"],
    method="spearman"
)

print("Коефіцієнт Пірсона:", pearson)
print("Коефіцієнт Спірмена:", spearman)

Коефіцієнт Пірсона та Спірмена для Global_active_power і Global_intensity
Коефіцієнт Пірсона: 0.9988886002095858
Коефіцієнт Спірмена: 0.9953719367299725

In [12]:
print("One Hot Encoding категоріального атрибута Date")

sample_dates = df_clean["Date"].drop_duplicates().head(5)

df_ohe = df_clean[
    df_clean["Date"].isin(sample_dates)
].copy()

df_encoded = pd.get_dummies(
    df_ohe,
    columns=["Date"]
)

print("Розмір після One Hot Encoding:", df_encoded.shape)
display(df_encoded.head())

print("Стовпці після One Hot Encoding:")
print(df_encoded.columns)

One Hot Encoding категоріального атрибута Date
Розмір після One Hot Encoding: (6156, 13)

,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Date_16/12/2006,Date_17/12/2006,Date_18/12/2006,Date_19/12/2006,Date_20/12/2006
0,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.0,True,False,False,False,False
1,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.0,True,False,False,False,False
2,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.0,True,False,False,False,False
3,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.0,True,False,False,False,False
4,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.0,True,False,False,False,False

Стовпці після One Hot Encoding:
Index(['Time', 'Global_active_power', 'Global_reactive_power', 'Voltage',
       'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3', 'Date_16/12/2006', 'Date_17/12/2006',
       'Date_18/12/2006', 'Date_19/12/2006', 'Date_20/12/2006'],
      dtype='str')