In [53]:
import pandas as pd
import requests
import os
import glob
import timeit

In [55]:
!python vhi_downloader.py

Область 1: файл вже існує, пропуск.
Область 2: файл вже існує, пропуск.
Область 3: файл вже існує, пропуск.
Область 4: файл вже існує, пропуск.
Область 5: файл вже існує, пропуск.
Область 6: файл вже існує, пропуск.
Область 7: файл вже існує, пропуск.
Область 8: файл вже існує, пропуск.
Область 9: файл вже існує, пропуск.
Область 10: файл вже існує, пропуск.
Область 11: файл вже існує, пропуск.
Область 12: файл вже існує, пропуск.
Область 13: файл вже існує, пропуск.
Область 14: файл вже існує, пропуск.
Область 15: файл вже існує, пропуск.
Область 16: файл вже існує, пропуск.
Область 17: файл вже існує, пропуск.
Область 18: файл вже існує, пропуск.
Область 19: файл вже існує, пропуск.
Область 20: файл вже існує, пропуск.
Область 21: файл вже існує, пропуск.
Область 22: файл вже існує, пропуск.
Область 23: файл вже існує, пропуск.
Область 24: файл вже існує, пропуск.
Область 25: файл вже існує, пропуск.
Область 26: файл вже існує, пропуск.
Область 27: файл вже існує, пропуск.

In [56]:
%run vhi_cleaning.py

       Year  Week    SMN     SMT    VCI    TCI    VHI  Province_ID_NOAA  \
33540  1982     1  0.068  263.59  63.47  28.34   45.9                24
33541  1982     2  0.074  265.78  67.62  23.05  45.34                24
33542  1982     3  0.076  267.19  69.37   20.4  44.88                24
33543  1982     4  0.075  268.57  65.26  17.93   41.6                24
33544  1982     5  0.072  269.24  58.58   20.0  39.29                24

            Area  Area_ID
33540  Вінницька        1
33541  Вінницька        1
33542  Вінницька        1
33543  Вінницька        1
33544  Вінницька        1

Розмір dataframe: (60372, 10)
Кількість пропусків:
Year                0
Week                0
SMN                 0
SMT                 0
VCI                 0
TCI                 0
VHI                 0
Province_ID_NOAA    0
Area                0
Area_ID             0
dtype: int64

Перевірка зміни індексів областей:
       Province_ID_NOAA  Area_ID               Area
33540                24        1          Вінницька
35776                25        2          Волинська
49192                 5        3   Дніпропетровська
51428                 6        4           Донецька
40248                27        5        Житомирська
31304                23        6       Закарпатська
38012                26        7         Запорізька
53664                 7        8  Івано-Франківська
2236                 11        9           Київська
6708                 13       10     Кіровоградська
8944                 14       11          Луганська
11180                15       12          Львівська
13416                16       13       Миколаївська
15652                17       14            Одеська
17888                18       15         Полтавська
20124                19       16         Рівненська
26832                21       17            Сумська
29068                22       18      Тернопільська
55900                 8       19         Харківська
58136                 9       20         Херсонська
0                    10       21        Хмельницька
22360                 1       22          Черкаська
44720                 3       23        Чернівецька
42484                 2       24       Чернігівська
46956                 4       25            АР Крим
4472                 12       26            м. Київ
24596                20       27     м. Севастополь

Очищений dataframe збережено у файл vhi_cleaned.csv

In [58]:
print(df.head())
print(df.shape)

   Year  Week    SMN     SMT    VCI    TCI    VHI  Province_ID_NOAA  \
0  1982     1  0.079  267.92  43.33  29.71  36.52                 9
1  1982     2  0.074  267.83  42.28  28.60  35.44                 9
2  1982     3  0.076  267.98  44.17  28.60  36.38                 9
3  1982     4  0.077  268.75  45.15  28.16  36.66                 9
4  1982     5  0.077  269.44  44.22  28.30  36.26                 9

         Area  Area_ID
0  Херсонська       20
1  Херсонська       20
2  Херсонська       20
3  Херсонська       20
4  Херсонська       20
(2236, 10)

In [59]:
print("4.1 Реалізувати процедуру для формування вибірки ряду VHI за областю та роком")

4.1 Реалізувати процедуру для формування вибірки ряду VHI за областю та роком

In [60]:
def get_vhi_series(df, province_id, year):
    result = df[
        (df["Area_ID"] == province_id) &
        (df["Year"] == year)
    ][["Week", "VHI"]]

    return result

In [61]:
print("VHI для області 1 за 2020 рік")
get_vhi_series(df, 1, 2020).head()

VHI для області 1 за 2020 рік

Empty DataFrame
Columns: [Week, VHI]
Index: []

In [62]:
print("4.2 Максимальне та мінімальне значення VHI")

4.2 Максимальне та мінімальне значення VHI

In [63]:
def get_vhi_extremes(df, province_id, year):
    data = df[
        (df["Area_ID"] == province_id) &
        (df["Year"] == year)
    ]

    return {
        "min_vhi": data["VHI"].min(),
        "max_vhi": data["VHI"].max()
    }

In [65]:
get_vhi_extremes(df, 1, 2020)

{'min_vhi': nan, 'max_vhi': nan}

In [66]:
print(sorted(df["Year"].unique()))

[np.int64(1982), np.int64(1983), np.int64(1984), np.int64(1985), np.int64(1986), np.int64(1987), np.int64(1988), np.int64(1989), np.int64(1990), np.int64(1991), np.int64(1992), np.int64(1993), np.int64(1994), np.int64(1995), np.int64(1996), np.int64(1997), np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024)]

In [67]:
df[df["Year"] == 2020].head()

,Year,Week,SMN,SMT,VCI,TCI,VHI,Province_ID_NOAA,Area,Area_ID
1976,2020,1,0.151,274.62,82.93,8.95,45.94,9,Херсонська,20
1977,2020,2,0.147,275.01,84.76,5.80,45.28,9,Херсонська,20
1978,2020,3,0.141,274.99,84.26,5.09,44.67,9,Херсонська,20
1979,2020,4,0.139,275.70,84.73,4.51,44.62,9,Херсонська,20
1980,2020,5,0.143,276.68,85.76,3.35,44.56,9,Херсонська,20

In [68]:
df.groupby("Year").size()

Year
1982    52
1983    52
1984    52
1985    52
1986    52
1987    52
1988    52
1989    52
1990    52
1991    52
1992    52
1993    52
1994    52
1995    52
1996    52
1997    52
1998    52
1999    52
2000    52
2001    52
2002    52
2003    52
2004    52
2005    52
2006    52
2007    52
2008    52
2009    52
2010    52
2011    52
2012    52
2013    52
2014    52
2015    52
2016    52
2017    52
2018    52
2019    52
2020    52
2021    52
2022    52
2023    52
2024    52
dtype: int64

In [69]:
df[["Year", "Area_ID"]].drop_duplicates().head(20)

     Year  Area_ID
0    1982       20
52   1983       20
104  1984       20
156  1985       20
208  1986       20
260  1987       20
312  1988       20
364  1989       20
416  1990       20
468  1991       20
520  1992       20
572  1993       20
624  1994       20
676  1995       20
728  1996       20
780  1997       20
832  1998       20
884  1999       20
936  2000       20
988  2001       20

In [70]:
df = pd.read_csv("vhi_cleaned.csv")

print(df.head())
print(df.shape)
print(df["Area_ID"].unique())

   Year  Week    SMN     SMT    VCI    TCI    VHI  Province_ID_NOAA  \
0  1982     1  0.068  263.59  63.47  28.34  45.90                24
1  1982     2  0.074  265.78  67.62  23.05  45.34                24
2  1982     3  0.076  267.19  69.37  20.40  44.88                24
3  1982     4  0.075  268.57  65.26  17.93  41.60                24
4  1982     5  0.072  269.24  58.58  20.00  39.29                24

        Area  Area_ID
0  Вінницька        1
1  Вінницька        1
2  Вінницька        1
3  Вінницька        1
4  Вінницька        1
(60372, 10)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]

In [71]:
get_vhi_series(df, 1, 2020).head()

      Week    VHI
1976     1  40.92
1977     2  43.19
1978     3  44.74
1979     4  45.29
1980     5  44.80

In [72]:
get_vhi_extremes(df, 1, 2020)

{'min_vhi': np.float64(34.48), 'max_vhi': np.float64(64.12)}

In [73]:
print("4.3 Роки з екстремальними значеннями VHI")

4.3 Роки з екстремальними значеннями VHI

In [74]:
def get_extreme_years(df, province_id):
    data = df[df["Area_ID"] == province_id]

    min_row = data.loc[data["VHI"].idxmin()]
    max_row = data.loc[data["VHI"].idxmax()]

    return {
        "year_min": min_row["Year"],
        "vhi_min": min_row["VHI"],
        "year_max": max_row["Year"],
        "vhi_max": max_row["VHI"]
    }

In [75]:
get_extreme_years(df, 1)

{'year_min': np.int64(2000),
 'vhi_min': np.float64(11.25),
 'year_max': np.int64(1997),
 'vhi_max': np.float64(82.64)}

In [76]:
print("4.4 Пошук років з екстремальною посухою")

4.4 Пошук років з екстремальною посухою

In [77]:
def drought_years(df, province_id, threshold=15):
    data = df[
        (df["Area_ID"] == province_id) &
        (df["VHI"] < threshold)
    ]

    return sorted(data["Year"].unique())

In [78]:
drought_years(df, 1)

[np.int64(2000)]

In [79]:
print("4.5 Пошук років з помірною посухою")

4.5 Пошук років з помірною посухою

In [80]:
def moderate_drought_years(df, province_id):
    data = df[
        (df["Area_ID"] == province_id) &
        (df["VHI"] >= 15) &
        (df["VHI"] < 35)
    ]

    return sorted(data["Year"].unique())

In [81]:
moderate_drought_years(df, 1)

[np.int64(1982),
 np.int64(1983),
 np.int64(1984),
 np.int64(1985),
 np.int64(1986),
 np.int64(1987),
 np.int64(1988),
 np.int64(1989),
 np.int64(1990),
 np.int64(1991),
 np.int64(1992),
 np.int64(1993),
 np.int64(1994),
 np.int64(1995),
 np.int64(1996),
 np.int64(1997),
 np.int64(1999),
 np.int64(2000),
 np.int64(2003),
 np.int64(2007),
 np.int64(2009),
 np.int64(2012),
 np.int64(2013),
 np.int64(2015),
 np.int64(2016),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024)]

In [82]:
print("4.6 Пошук років з сильною посухою")

4.6 Пошук років з сильною посухою

In [83]:
def severe_drought_years(df, province_id):
    data = df[
        (df["Area_ID"] == province_id) &
        (df["VHI"] >= 0) &
        (df["VHI"] < 15)
    ]

    return sorted(data["Year"].unique())

In [84]:
severe_drought_years(df, 1)

[np.int64(2000)]